### ISSUE TITLE
Question about xkbcommon

### ISSUE THREAD

**Issue by Narrat** [milgra/wcp#1]
Hello,
a small question arose while trying to compile this project.
In the `meson.build` the dep `xkbcommon` is required for compilation. But the `README.md` doesn't mention it and at a first glance I didn't see any includes regarding that lib?
Did I miss something or could this dep removed from the `meson.build`?

**Comment by milgra** [comment]
Hi, I was preparing keyboard control and added the package in advance but doesn't use it yet. So I just removed it for now and created a new release, thank you for pointing that out!
