### ISSUE TITLE
Transparent background is gone after some seconds.

### ISSUE THREAD

**Issue by lidgnulinux** [milgra/wcp#2]
Hello, I'm trying to set the background to 60% transparent on `main.css`. It's applied but within a second it's gone (back to normal color / not transparent).

here is my main.css : 

```
#main {
    border-radius: 10px;
    background-color: #00000099;
}

.... (The rest of the css)
```

Any fix to this problem ? Thanks.

**Comment by milgra** [comment]
Hi, fixed in 0.52, thank you for reporting it!
