### ISSUE TITLE
Place wcp to bottom-right of screen.

### ISSUE THREAD

**Issue by lidgnulinux** [milgra/wcp#3]
Hello I'm trying to place wcp to bottom-right of screen and still get no luck.
I'm adding

```
....
position: relative;
bottom: 0;
right: 0;
....
```
To main.css (#main) but still show at top of the screen.

I have 1366x768 screen. Any clue ? Thanks.

**Comment by milgra** [comment]
Hi, CSS works inside the window only, I will add window alignment options to wcp soon.

**Comment by lidgnulinux** [comment]
Thanks @milgra

**Comment by milgra** [comment]
Hi, with the latest release you can start wcp with
`wcp -a rb`
to anchor wcp to the right bottom.

**Comment by lidgnulinux** [comment]
Wow, it works, great.
